"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-19 19:28:00.726218
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('TEACHER', 'ADMIN', name='userrole', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('exam_id', sa.Uuid(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_course_id'), 'audit_logs', ['course_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_exam_id'), 'audit_logs', ['exam_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_courses_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_index(op.f('ix_courses_owner_id'), 'courses', ['owner_id'], unique=False)
    op.create_index('uq_courses_owner_code', 'courses', ['owner_id', 'code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('course_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'INSTRUCTOR', 'VIEWER', name='courserole', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_members_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_course_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_members')),
    sa.UniqueConstraint('course_id', 'user_id', name='uq_course_members_course_user')
    )
    op.create_index(op.f('ix_course_members_user_id'), 'course_members', ['user_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('pass_percentage', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('confidence_high_threshold', sa.Float(), nullable=True),
    sa.Column('confidence_review_threshold', sa.Float(), nullable=True),
    sa.Column('paper_status', sa.Enum('NONE', 'PROCESSING', 'PARSED', 'FAILED', name='paperstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('paper_storage_key', sa.String(length=500), nullable=True),
    sa.Column('paper_filename', sa.String(length=300), nullable=True),
    sa.Column('paper_sha256', sa.String(length=64), nullable=True),
    sa.Column('paper_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('paper_error', sa.Text(), nullable=True),
    sa.Column('declared_total_marks', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('questions_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_exams_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_exams_created_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exams'))
    )
    op.create_index(op.f('ix_exams_course_id'), 'exams', ['course_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='resourcestatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_resources_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_resources_uploaded_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    op.create_index(op.f('ix_resources_course_id'), 'resources', ['course_id'], unique=False)
    op.create_index('uq_resources_course_sha', 'resources', ['course_id', 'content_sha256'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('roll_number', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_students_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    op.create_index(op.f('ix_students_course_id'), 'students', ['course_id'], unique=False)
    op.create_index('uq_students_course_roll', 'students', ['course_id', 'roll_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('answer_sheet_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='batchstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_answer_sheet_batches_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_answer_sheet_batches_exam_id_exams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_sheet_batches'))
    )
    op.create_index(op.f('ix_answer_sheet_batches_exam_id'), 'answer_sheet_batches', ['exam_id'], unique=False)
    op.create_table('exam_analytics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_analytics_exam_id_exams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_analytics')),
    sa.UniqueConstraint('exam_id', name=op.f('uq_exam_analytics_exam_id'))
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('PROCESS_RESOURCE', 'PARSE_QUESTION_PAPER', 'GENERATE_RUBRIC', 'PROCESS_ANSWER_SHEET', 'EVALUATE_ANSWER_SHEET', 'GENERATE_FEEDBACK', name='jobkind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('exam_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'REQUIRES_REVIEW', name='jobstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('progress_message', sa.String(length=300), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_processing_jobs_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_processing_jobs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_processing_jobs_exam_id_exams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    op.create_index(op.f('ix_processing_jobs_course_id'), 'processing_jobs', ['course_id'], unique=False)
    op.create_index('ix_processing_jobs_entity', 'processing_jobs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_exam_id'), 'processing_jobs', ['exam_id'], unique=False)
    op.create_index('uq_processing_jobs_active', 'processing_jobs', ['kind', 'entity_id'], unique=True, postgresql_where=sa.text("status IN ('QUEUED','PROCESSING')"))
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('max_marks', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('choice_group', sa.String(length=50), nullable=True),
    sa.Column('choice_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('choice_count >= 1', name=op.f('ck_questions_choice_count_positive')),
    sa.CheckConstraint('max_marks >= 0', name=op.f('ck_questions_max_marks_nonneg')),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_questions_exam_id_exams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('exam_id', 'number', name='uq_questions_exam_number')
    )
    op.create_table('resource_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_files_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_resource_files_storage_key'))
    )
    op.create_index(op.f('ix_resource_files_resource_id'), 'resource_files', ['resource_id'], unique=False)
    op.create_table('rubrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_rubrics_exam_id_exams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubrics')),
    sa.UniqueConstraint('exam_id', name=op.f('uq_rubrics_exam_id'))
    )
    op.create_table('answer_sheets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'EVALUATING', 'EVALUATED', 'FAILED', name='sheetstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('detected_name', sa.String(length=200), nullable=True),
    sa.Column('detected_roll_number', sa.String(length=64), nullable=True),
    sa.Column('identity_confidence', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['answer_sheet_batches.id'], name=op.f('fk_answer_sheets_batch_id_answer_sheet_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_answer_sheets_exam_id_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_answer_sheets_student_id_students'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_sheets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_answer_sheets_storage_key'))
    )
    op.create_index(op.f('ix_answer_sheets_exam_id'), 'answer_sheets', ['exam_id'], unique=False)
    op.create_index(op.f('ix_answer_sheets_student_id'), 'answer_sheets', ['student_id'], unique=False)
    op.create_index('uq_answer_sheets_exam_sha', 'answer_sheets', ['exam_id', 'sha256'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_answer_sheets_exam_student', 'answer_sheets', ['exam_id', 'student_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND student_id IS NOT NULL'))
    op.create_table('resource_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('resource_file_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=300), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_resource_chunks_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_file_id'], ['resource_files.id'], name=op.f('fk_resource_chunks_resource_file_id_resource_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_chunks_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_chunks')),
    sa.UniqueConstraint('resource_id', 'chunk_index', name='uq_resource_chunks_resource_idx')
    )
    op.create_index(op.f('ix_resource_chunks_course_id'), 'resource_chunks', ['course_id'], unique=False)
    op.create_table('rubric_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SUPERSEDED', name='rubricversionstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('source', sa.Enum('AI', 'TEACHER', name='rubricsource', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_rubric_versions_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_rubric_versions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], name=op.f('fk_rubric_versions_rubric_id_rubrics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubric_versions')),
    sa.UniqueConstraint('rubric_id', 'version_number', name='uq_rubric_versions_rubric_number')
    )
    op.create_index(op.f('ix_rubric_versions_rubric_id'), 'rubric_versions', ['rubric_id'], unique=False)
    op.create_index('uq_rubric_versions_one_approved', 'rubric_versions', ['rubric_id'], unique=True, postgresql_where=sa.text("status = 'APPROVED'"))
    op.create_index('uq_rubric_versions_one_draft', 'rubric_versions', ['rubric_id'], unique=True, postgresql_where=sa.text("status = 'DRAFT'"))
    op.create_table('subquestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('max_marks', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.CheckConstraint('max_marks >= 0', name=op.f('ck_subquestions_max_marks_nonneg')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_subquestions_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subquestions')),
    sa.UniqueConstraint('question_id', 'label', name='uq_subquestions_question_label')
    )
    op.create_index(op.f('ix_subquestions_question_id'), 'subquestions', ['question_id'], unique=False)
    op.create_table('answer_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('answer_sheet_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheets.id'], name=op.f('fk_answer_pages_answer_sheet_id_answer_sheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_pages')),
    sa.UniqueConstraint('answer_sheet_id', 'page_number', name='uq_answer_pages_sheet_page'),
    sa.UniqueConstraint('image_key', name=op.f('uq_answer_pages_image_key'))
    )
    op.create_table('answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('answer_sheet_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('subquestion_id', sa.Uuid(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.Uuid(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_missing', sa.Boolean(), nullable=False),
    sa.Column('has_diagram', sa.Boolean(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('mapping_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheets.id'], name=op.f('fk_answers_answer_sheet_id_answer_sheets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['corrected_by'], ['users.id'], name=op.f('fk_answers_corrected_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answers_question_id_questions')),
    sa.ForeignKeyConstraint(['subquestion_id'], ['subquestions.id'], name=op.f('fk_answers_subquestion_id_subquestions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers'))
    )
    op.create_index(op.f('ix_answers_answer_sheet_id'), 'answers', ['answer_sheet_id'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index('uq_answers_unit_question', 'answers', ['answer_sheet_id', 'question_id'], unique=True, postgresql_where=sa.text('subquestion_id IS NULL'))
    op.create_index('uq_answers_unit_sub', 'answers', ['answer_sheet_id', 'question_id', 'subquestion_id'], unique=True, postgresql_where=sa.text('subquestion_id IS NOT NULL'))
    op.create_table('rubric_criteria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rubric_version_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('subquestion_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_points', sa.Text(), nullable=True),
    sa.Column('max_marks', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('generation_confidence', sa.Float(), nullable=True),
    sa.CheckConstraint('max_marks > 0', name=op.f('ck_rubric_criteria_max_marks_positive')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_rubric_criteria_question_id_questions')),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], name=op.f('fk_rubric_criteria_rubric_version_id_rubric_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subquestion_id'], ['subquestions.id'], name=op.f('fk_rubric_criteria_subquestion_id_subquestions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubric_criteria'))
    )
    op.create_index(op.f('ix_rubric_criteria_question_id'), 'rubric_criteria', ['question_id'], unique=False)
    op.create_index(op.f('ix_rubric_criteria_rubric_version_id'), 'rubric_criteria', ['rubric_version_id'], unique=False)
    op.create_index(op.f('ix_rubric_criteria_subquestion_id'), 'rubric_criteria', ['subquestion_id'], unique=False)
    op.create_table('student_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('answer_sheet_id', sa.Uuid(), nullable=False),
    sa.Column('total', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_total', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PROVISIONAL', 'FINAL', name='resultstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('pending_reviews', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total >= 0 AND total <= max_total', name=op.f('ck_student_results_total_in_range')),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheets.id'], name=op.f('fk_student_results_answer_sheet_id_answer_sheets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_student_results_exam_id_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_results_student_id_students'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_results')),
    sa.UniqueConstraint('answer_sheet_id', name=op.f('uq_student_results_answer_sheet_id'))
    )
    op.create_index(op.f('ix_student_results_exam_id'), 'student_results', ['exam_id'], unique=False)
    op.create_table('topic_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('answer_sheet_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheets.id'], name=op.f('fk_topic_results_answer_sheet_id_answer_sheets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_topic_results_exam_id_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_topic_results_student_id_students'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_results')),
    sa.UniqueConstraint('answer_sheet_id', 'topic', name='uq_topic_results_sheet_topic')
    )
    op.create_index(op.f('ix_topic_results_exam_id'), 'topic_results', ['exam_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('rubric_version_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', name='evaluationstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('text_source', sa.Enum('ORIGINAL', 'CORRECTED', name='textsource', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('answer_text_snapshot', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('ai_total', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_total', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('mapping_confidence', sa.Float(), nullable=True),
    sa.Column('retrieval_confidence', sa.Float(), nullable=True),
    sa.Column('rubric_confidence', sa.Float(), nullable=True),
    sa.Column('evaluation_confidence', sa.Float(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ai_total >= 0 AND ai_total <= max_total', name=op.f('ck_evaluations_total_in_range')),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_evaluations_answer_id_answers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], name=op.f('fk_evaluations_rubric_version_id_rubric_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations')),
    sa.UniqueConstraint('answer_id', 'attempt', name='uq_evaluations_answer_attempt')
    )
    op.create_index(op.f('ix_evaluations_answer_id'), 'evaluations', ['answer_id'], unique=False)
    op.create_index(op.f('ix_evaluations_rubric_version_id'), 'evaluations', ['rubric_version_id'], unique=False)
    op.create_index('uq_evaluations_current', 'evaluations', ['answer_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('ocr_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('answer_page_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('has_diagram', sa.Boolean(), nullable=False),
    sa.Column('unreadable_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('header', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_ocr_results_confidence_range')),
    sa.ForeignKeyConstraint(['answer_page_id'], ['answer_pages.id'], name=op.f('fk_ocr_results_answer_page_id_answer_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocr_results')),
    sa.UniqueConstraint('answer_page_id', 'version', name='uq_ocr_results_page_version')
    )
    op.create_index(op.f('ix_ocr_results_answer_page_id'), 'ocr_results', ['answer_page_id'], unique=False)
    op.create_index('uq_ocr_results_current', 'ocr_results', ['answer_page_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('answer_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('answer_sheet_id', sa.Uuid(), nullable=False),
    sa.Column('answer_id', sa.Uuid(), nullable=True),
    sa.Column('answer_page_id', sa.Uuid(), nullable=False),
    sa.Column('ocr_result_id', sa.Uuid(), nullable=False),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.Column('detected_label', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('AI', 'RULE', 'TEACHER', name='mappingmethod', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_answer_mappings_confidence_range')),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_answer_mappings_answer_id_answers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['answer_page_id'], ['answer_pages.id'], name=op.f('fk_answer_mappings_answer_page_id_answer_pages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheets.id'], name=op.f('fk_answer_mappings_answer_sheet_id_answer_sheets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ocr_result_id'], ['ocr_results.id'], name=op.f('fk_answer_mappings_ocr_result_id_ocr_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_mappings'))
    )
    op.create_index(op.f('ix_answer_mappings_answer_id'), 'answer_mappings', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_mappings_answer_page_id'), 'answer_mappings', ['answer_page_id'], unique=False)
    op.create_index(op.f('ix_answer_mappings_answer_sheet_id'), 'answer_mappings', ['answer_sheet_id'], unique=False)
    op.create_table('confidence_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('answer_sheet_id', sa.Uuid(), nullable=False),
    sa.Column('answer_id', sa.Uuid(), nullable=True),
    sa.Column('evaluation_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('LOW_OCR', 'LOW_MAPPING', 'LOW_RETRIEVAL', 'LOW_RUBRIC', 'LOW_EVALUATION', 'LOW_OVERALL', 'MISSING_ANSWER', 'UNREADABLE', 'STUDENT_UNIDENTIFIED', 'INVALID_AI_OUTPUT', 'EVALUATION_FAILED', name='flagkind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('severity', sa.Enum('RECOMMENDED', 'MANDATORY', name='flagseverity', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_confidence_flags_answer_id_answers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheets.id'], name=op.f('fk_confidence_flags_answer_sheet_id_answer_sheets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_confidence_flags_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confidence_flags'))
    )
    op.create_index(op.f('ix_confidence_flags_answer_id'), 'confidence_flags', ['answer_id'], unique=False)
    op.create_index(op.f('ix_confidence_flags_answer_sheet_id'), 'confidence_flags', ['answer_sheet_id'], unique=False)
    op.create_index(op.f('ix_confidence_flags_evaluation_id'), 'confidence_flags', ['evaluation_id'], unique=False)
    op.create_table('evaluation_criteria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('rubric_criterion_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('satisfied', sa.Boolean(), nullable=False),
    sa.Column('partial', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('missing_points', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_evaluation_criteria_confidence_range')),
    sa.CheckConstraint('score >= 0 AND score <= max_score', name=op.f('ck_evaluation_criteria_score_in_range')),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_evaluation_criteria_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rubric_criterion_id'], ['rubric_criteria.id'], name=op.f('fk_evaluation_criteria_rubric_criterion_id_rubric_criteria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_criteria')),
    sa.UniqueConstraint('evaluation_id', 'rubric_criterion_id', name='uq_evaluation_criteria_eval_criterion')
    )
    op.create_index(op.f('ix_evaluation_criteria_evaluation_id'), 'evaluation_criteria', ['evaluation_id'], unique=False)
    op.create_table('evaluation_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('resource_title', sa.String(length=300), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=300), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('text_snapshot', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['resource_chunks.id'], name=op.f('fk_evaluation_sources_chunk_id_resource_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_evaluation_sources_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_evaluation_sources_resource_id_resources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_sources'))
    )
    op.create_index(op.f('ix_evaluation_sources_evaluation_id'), 'evaluation_sources', ['evaluation_id'], unique=False)
    op.create_table('teacher_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('answer_sheet_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', name='reviewstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('decision', sa.Enum('ACCEPTED', 'OVERRIDDEN', name='reviewdecision', native_enum=False, create_constraint=True, length=40), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_sheet_id'], ['answer_sheets.id'], name=op.f('fk_teacher_reviews_answer_sheet_id_answer_sheets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_teacher_reviews_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_teacher_reviews_reviewer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_reviews')),
    sa.UniqueConstraint('evaluation_id', name=op.f('uq_teacher_reviews_evaluation_id'))
    )
    op.create_index(op.f('ix_teacher_reviews_answer_sheet_id'), 'teacher_reviews', ['answer_sheet_id'], unique=False)
    op.create_table('teacher_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_criterion_id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=True),
    sa.Column('ai_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('teacher_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(reason)) > 0', name=op.f('ck_teacher_overrides_reason_not_blank')),
    sa.CheckConstraint('teacher_score >= 0 AND final_score >= 0', name=op.f('ck_teacher_overrides_scores_nonneg')),
    sa.ForeignKeyConstraint(['evaluation_criterion_id'], ['evaluation_criteria.id'], name=op.f('fk_teacher_overrides_evaluation_criterion_id_evaluation_criteria'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_teacher_overrides_evaluation_id_evaluations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['teacher_reviews.id'], name=op.f('fk_teacher_overrides_review_id_teacher_reviews'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_teacher_overrides_teacher_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_overrides'))
    )
    op.create_index(op.f('ix_teacher_overrides_evaluation_id'), 'teacher_overrides', ['evaluation_id'], unique=False)
    op.create_index('uq_teacher_overrides_active', 'teacher_overrides', ['evaluation_criterion_id'], unique=True, postgresql_where=sa.text('is_active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_teacher_overrides_active', table_name='teacher_overrides', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_teacher_overrides_evaluation_id'), table_name='teacher_overrides')
    op.drop_table('teacher_overrides')
    op.drop_index(op.f('ix_teacher_reviews_answer_sheet_id'), table_name='teacher_reviews')
    op.drop_table('teacher_reviews')
    op.drop_index(op.f('ix_evaluation_sources_evaluation_id'), table_name='evaluation_sources')
    op.drop_table('evaluation_sources')
    op.drop_index(op.f('ix_evaluation_criteria_evaluation_id'), table_name='evaluation_criteria')
    op.drop_table('evaluation_criteria')
    op.drop_index(op.f('ix_confidence_flags_evaluation_id'), table_name='confidence_flags')
    op.drop_index(op.f('ix_confidence_flags_answer_sheet_id'), table_name='confidence_flags')
    op.drop_index(op.f('ix_confidence_flags_answer_id'), table_name='confidence_flags')
    op.drop_table('confidence_flags')
    op.drop_index(op.f('ix_answer_mappings_answer_sheet_id'), table_name='answer_mappings')
    op.drop_index(op.f('ix_answer_mappings_answer_page_id'), table_name='answer_mappings')
    op.drop_index(op.f('ix_answer_mappings_answer_id'), table_name='answer_mappings')
    op.drop_table('answer_mappings')
    op.drop_index('uq_ocr_results_current', table_name='ocr_results', postgresql_where=sa.text('is_current'))
    op.drop_index(op.f('ix_ocr_results_answer_page_id'), table_name='ocr_results')
    op.drop_table('ocr_results')
    op.drop_index('uq_evaluations_current', table_name='evaluations', postgresql_where=sa.text('is_current'))
    op.drop_index(op.f('ix_evaluations_rubric_version_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_answer_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_topic_results_exam_id'), table_name='topic_results')
    op.drop_table('topic_results')
    op.drop_index(op.f('ix_student_results_exam_id'), table_name='student_results')
    op.drop_table('student_results')
    op.drop_index(op.f('ix_rubric_criteria_subquestion_id'), table_name='rubric_criteria')
    op.drop_index(op.f('ix_rubric_criteria_rubric_version_id'), table_name='rubric_criteria')
    op.drop_index(op.f('ix_rubric_criteria_question_id'), table_name='rubric_criteria')
    op.drop_table('rubric_criteria')
    op.drop_index('uq_answers_unit_sub', table_name='answers', postgresql_where=sa.text('subquestion_id IS NOT NULL'))
    op.drop_index('uq_answers_unit_question', table_name='answers', postgresql_where=sa.text('subquestion_id IS NULL'))
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_answer_sheet_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_table('answer_pages')
    op.drop_index(op.f('ix_subquestions_question_id'), table_name='subquestions')
    op.drop_table('subquestions')
    op.drop_index('uq_rubric_versions_one_draft', table_name='rubric_versions', postgresql_where=sa.text("status = 'DRAFT'"))
    op.drop_index('uq_rubric_versions_one_approved', table_name='rubric_versions', postgresql_where=sa.text("status = 'APPROVED'"))
    op.drop_index(op.f('ix_rubric_versions_rubric_id'), table_name='rubric_versions')
    op.drop_table('rubric_versions')
    op.drop_index(op.f('ix_resource_chunks_course_id'), table_name='resource_chunks')
    op.drop_table('resource_chunks')
    op.drop_index('uq_answer_sheets_exam_student', table_name='answer_sheets', postgresql_where=sa.text('deleted_at IS NULL AND student_id IS NOT NULL'))
    op.drop_index('uq_answer_sheets_exam_sha', table_name='answer_sheets', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_answer_sheets_student_id'), table_name='answer_sheets')
    op.drop_index(op.f('ix_answer_sheets_exam_id'), table_name='answer_sheets')
    op.drop_table('answer_sheets')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_resource_files_resource_id'), table_name='resource_files')
    op.drop_table('resource_files')
    op.drop_table('questions')
    op.drop_index('uq_processing_jobs_active', table_name='processing_jobs', postgresql_where=sa.text("status IN ('QUEUED','PROCESSING')"))
    op.drop_index(op.f('ix_processing_jobs_exam_id'), table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_entity', table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_course_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_table('exam_analytics')
    op.drop_index(op.f('ix_answer_sheet_batches_exam_id'), table_name='answer_sheet_batches')
    op.drop_table('answer_sheet_batches')
    op.drop_index('uq_students_course_roll', table_name='students', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_students_course_id'), table_name='students')
    op.drop_table('students')
    op.drop_index('uq_resources_course_sha', table_name='resources', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_resources_course_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_exams_course_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_course_members_user_id'), table_name='course_members')
    op.drop_table('course_members')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('uq_courses_owner_code', table_name='courses', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_courses_owner_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_audit_logs_exam_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_course_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_users_email_lower', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    # ### end Alembic commands ###
