"""StorageProvider abstraction + local-disk implementation.

Keys are always generated by the server (never derived from user filenames) and are
validated and confined to the storage root, so path traversal is not possible.
"""
from __future__ import annotations

import hashlib
import os
import re
import shutil
import tempfile
from abc import ABC, abstractmethod
from collections.abc import Iterable, Iterator
from functools import lru_cache
from pathlib import Path

from app.core.config import settings

_KEY_RE = re.compile(r"^[A-Za-z0-9_\-]+(/[A-Za-z0-9_\-]+)*(\.[A-Za-z0-9]{1,8})?$")


class StorageError(RuntimeError):
    pass


class StorageProvider(ABC):
    @abstractmethod
    def save_stream(self, key: str, chunks: Iterable[bytes], *, max_bytes: int) -> tuple[int, str]:
        """Persist chunks under `key`; returns (size_bytes, sha256). Raises StorageError if max_bytes is exceeded."""

    @abstractmethod
    def save_bytes(self, key: str, data: bytes) -> None: ...

    @abstractmethod
    def read_bytes(self, key: str) -> bytes: ...

    @abstractmethod
    def open_stream(self, key: str, chunk_size: int = 1024 * 256) -> Iterator[bytes]: ...

    @abstractmethod
    def exists(self, key: str) -> bool: ...

    @abstractmethod
    def delete(self, key: str) -> None: ...

    @abstractmethod
    def size(self, key: str) -> int: ...


class LocalStorage(StorageProvider):
    def __init__(self, root: str | Path):
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        if not _KEY_RE.match(key) or ".." in key:
            raise StorageError("invalid storage key")
        p = (self.root / key).resolve()
        if self.root not in p.parents:
            raise StorageError("storage key escapes the storage root")
        return p

    def save_stream(self, key: str, chunks: Iterable[bytes], *, max_bytes: int) -> tuple[int, str]:
        dest = self._path(key)
        dest.parent.mkdir(parents=True, exist_ok=True)
        h = hashlib.sha256()
        size = 0
        fd, tmp_name = tempfile.mkstemp(dir=dest.parent, prefix=".upload-")
        try:
            with os.fdopen(fd, "wb") as tmp:
                for chunk in chunks:
                    size += len(chunk)
                    if size > max_bytes:
                        raise StorageError("file exceeds the maximum allowed size")
                    h.update(chunk)
                    tmp.write(chunk)
            os.replace(tmp_name, dest)
        except BaseException:
            Path(tmp_name).unlink(missing_ok=True)
            raise
        return size, h.hexdigest()

    def save_bytes(self, key: str, data: bytes) -> None:
        self.save_stream(key, [data], max_bytes=len(data) + 1)

    def read_bytes(self, key: str) -> bytes:
        try:
            return self._path(key).read_bytes()
        except FileNotFoundError as e:
            raise StorageError(f"stored file is missing: {key}") from e

    def open_stream(self, key: str, chunk_size: int = 1024 * 256) -> Iterator[bytes]:
        p = self._path(key)
        if not p.is_file():
            raise StorageError(f"stored file is missing: {key}")
        with p.open("rb") as f:
            while chunk := f.read(chunk_size):
                yield chunk

    def exists(self, key: str) -> bool:
        return self._path(key).is_file()

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)

    def size(self, key: str) -> int:
        return self._path(key).stat().st_size

    def delete_prefix(self, prefix: str) -> None:
        d = self._path(prefix)
        if d.is_dir():
            shutil.rmtree(d, ignore_errors=True)


@lru_cache
def get_storage() -> StorageProvider:
    if settings.storage_backend == "local":
        return LocalStorage(settings.storage_local_root)
    raise StorageError(f"unsupported storage backend: {settings.storage_backend}")
